// Code generated by protoc-gen-go-micro. DO NOT EDIT.
// versions:
// - protoc-gen-go-micro v3.5.3
// - protoc              v3.21.4
// source: fns.proto

package mc_go_fns_proto

import (
	context "context"
	api "go.unistack.org/micro/v3/api"
	client "go.unistack.org/micro/v3/client"
)

var (
	InnServiceName = "InnService"

	InnServiceEndpoints = []api.Endpoint{
		{
			Name:    "InnService.GetInn",
			Path:    []string{"/getinn"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
)

func NewInnServiceEndpoints() []api.Endpoint {
	return InnServiceEndpoints
}

type InnServiceClient interface {
	GetInn(ctx context.Context, req *GetInnReq, opts ...client.CallOption) (*GetInnRsp, error)
}

type InnServiceServer interface {
	GetInn(ctx context.Context, req *GetInnReq, rsp *GetInnRsp) error
}
